import { Link } from "@tanstack/react-router";
import { ArrowLeft, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PageHeader } from "@/components/match-center/MatchCenterLayout";
import type { DemoEntity } from "@/lib/mc-demo/store";

/** Full-page stub shown when a `demo-*` id lands on a detail page.
 *  Real detail pages fetch rows from Supabase — demo entities don't exist there.
 *  This stub renders the same layout shell (breadcrumbs + header) plus a
 *  concise summary card, so navigation from list → detail never dead-ends.
 */
export function DemoDetailStub({
  entity,
  backLabel,
  backTo,
  parentLabel,
  parentTo,
}: {
  entity: DemoEntity;
  backLabel: string;
  backTo: string;
  parentLabel: string;
  parentTo: string;
}) {
  const { title, subtitle, facts, kindLabel } = describe(entity);
  return (
    <div>
      <div className="mb-4">
        <Button variant="ghost" size="sm" asChild>
          <Link to={backTo}>
            <ArrowLeft className="size-4 mr-1.5" /> {backLabel}
          </Link>
        </Button>
      </div>
      <PageHeader
        title={title}
        description={subtitle}
        breadcrumbs={[
          { label: "Match Center", to: "/match-center/dashboard" },
          { label: parentLabel, to: parentTo },
          { label: title },
        ]}
      />

      <div className="rounded-3xl border border-amber-500/30 bg-gradient-to-br from-amber-500/5 via-card to-card p-6">
        <div className="flex items-center gap-2 text-[11px] font-semibold uppercase tracking-widest text-amber-600 dark:text-amber-300">
          <Sparkles className="size-3.5" />
          {kindLabel} · Demo Data
        </div>
        <h2 className="mt-3 text-2xl font-bold tracking-tight">{title}</h2>
        {subtitle && <p className="mt-1 text-sm text-muted-foreground">{subtitle}</p>}

        <dl className="mt-5 grid gap-3 sm:grid-cols-2 md:grid-cols-3">
          {facts.map(({ label, value }) => (
            <div
              key={label}
              className="rounded-xl border border-border bg-background/60 p-3"
            >
              <dt className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground">
                {label}
              </dt>
              <dd className="mt-1 text-sm font-semibold tabular-nums">{value}</dd>
            </div>
          ))}
        </dl>

        <p className="mt-6 max-w-2xl text-xs text-muted-foreground">
          You're viewing sample content generated by Match Center's demo mode.
          Real profile, career, stats and timeline views are available on live
          academy data. Turn demo mode off in Settings to hide.
        </p>
      </div>
    </div>
  );
}

function describe(entity: DemoEntity): {
  title: string;
  subtitle: string;
  kindLabel: string;
  facts: Array<{ label: string; value: string }>;
} {
  if (entity.kind === "player") {
    const p = entity.player;
    const s = p.student;
    return {
      title: s?.name ?? "Demo player",
      subtitle: [p.cricket?.playing_role, p.primary_sport].filter(Boolean).join(" · "),
      kindLabel: "Player",
      facts: [
        { label: "Player ID", value: s?.player_id ?? "—" },
        { label: "Sport", value: p.primary_sport ?? "cricket" },
        { label: "Role", value: p.cricket?.playing_role ?? "—" },
        { label: "Batting", value: p.cricket?.batting_style ?? "—" },
        { label: "Bowling", value: p.cricket?.bowling_style ?? "—" },
        { label: "DOB", value: s?.dob ?? "—" },
      ],
    };
  }
  if (entity.kind === "team") {
    const t = entity.team;
    return {
      title: t.name,
      subtitle: [t.age_group, t.city, t.coach_name].filter(Boolean).join(" · "),
      kindLabel: "Team",
      facts: [
        { label: "Short name", value: t.short_name ?? "—" },
        { label: "Age group", value: t.age_group ?? "—" },
        { label: "Coach", value: t.coach_name ?? "—" },
        { label: "City", value: t.city ?? "—" },
        { label: "Status", value: t.status ?? "active" },
        { label: "Players", value: String(t.player_count ?? "—") },
      ],
    };
  }
  if (entity.kind === "tournament") {
    const t = entity.tournament;
    return {
      title: t.name,
      subtitle: [t.season, t.age_group, t.format].filter(Boolean).join(" · "),
      kindLabel: "Tournament",
      facts: [
        { label: "Type", value: t.tournament_type ?? "—" },
        { label: "Format", value: t.format ?? "—" },
        { label: "Overs", value: String(t.overs ?? "—") },
        { label: "Status", value: t.status ?? "—" },
        { label: "Start", value: t.start_date ?? "—" },
        { label: "End", value: t.end_date ?? "—" },
      ],
    };
  }
  const m = entity.match;
  return {
    title: `${m.team_a?.name ?? "Team A"} vs ${m.team_b?.name ?? "Team B"}`,
    subtitle: [m.match_format, m.ground_name, m.scheduled_date].filter(Boolean).join(" · "),
    kindLabel: "Match",
    facts: [
      { label: "Status", value: m.status ?? "—" },
      { label: "Format", value: m.match_format ?? "—" },
      { label: "Overs", value: String(m.overs ?? "—") },
      { label: "Result", value: m.result ?? (m.status === "live" ? "In progress" : "—") },
      { label: "Ground", value: m.ground_name ?? "—" },
      { label: "Date", value: m.scheduled_date ?? "—" },
    ],
  };
}
