/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StarPlayersRouteImport } from './routes/star-players'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PlatformAdminRouteImport } from './routes/platform-admin'
import { Route as ParentPortalRouteImport } from './routes/parent-portal'
import { Route as MatchCenterRouteImport } from './routes/match-center'
import { Route as FeesRouteImport } from './routes/fees'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppLaunchRouteImport } from './routes/app-launch'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlatformAdminIndexRouteImport } from './routes/platform-admin.index'
import { Route as MatchCenterIndexRouteImport } from './routes/match-center.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as ScorerMatchIdRouteImport } from './routes/scorer.$matchId'
import { Route as PlatformAdminSubscriptionsRouteImport } from './routes/platform-admin.subscriptions'
import { Route as PlatformAdminSettingsRouteImport } from './routes/platform-admin.settings'
import { Route as PlatformAdminNewRouteImport } from './routes/platform-admin.new'
import { Route as MatchSlugRouteImport } from './routes/match.$slug'
import { Route as MatchCenterWebsiteRouteImport } from './routes/match-center.website'
import { Route as MatchCenterTournamentsRouteImport } from './routes/match-center.tournaments'
import { Route as MatchCenterSettingsRouteImport } from './routes/match-center.settings'
import { Route as MatchCenterScorersRouteImport } from './routes/match-center.scorers'
import { Route as MatchCenterRecordsRouteImport } from './routes/match-center.records'
import { Route as MatchCenterRecognitionRouteImport } from './routes/match-center.recognition'
import { Route as MatchCenterProfileRouteImport } from './routes/match-center.profile'
import { Route as MatchCenterPerformanceRouteImport } from './routes/match-center.performance'
import { Route as MatchCenterMatchesRouteImport } from './routes/match-center.matches'
import { Route as MatchCenterLiveRouteImport } from './routes/match-center.live'
import { Route as MatchCenterLeaderboardsRouteImport } from './routes/match-center.leaderboards'
import { Route as MatchCenterInsightsRouteImport } from './routes/match-center.insights'
import { Route as MatchCenterDashboardRouteImport } from './routes/match-center.dashboard'
import { Route as MatchCenterCreateRouteImport } from './routes/match-center.create'
import { Route as MatchCenterAwardsRouteImport } from './routes/match-center.awards'
import { Route as MatchCenterAiInsightsRouteImport } from './routes/match-center.ai-insights'
import { Route as MSlugRouteImport } from './routes/m.$slug'
import { Route as DashboardSubscriptionRouteImport } from './routes/dashboard.subscription'
import { Route as DashboardStudentsRouteImport } from './routes/dashboard.students'
import { Route as DashboardSiteRouteImport } from './routes/dashboard.site'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardReportsRouteImport } from './routes/dashboard.reports'
import { Route as DashboardRemindersRouteImport } from './routes/dashboard.reminders'
import { Route as DashboardRegistrationsRouteImport } from './routes/dashboard.registrations'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardLeadsRouteImport } from './routes/dashboard.leads'
import { Route as DashboardInsightsRouteImport } from './routes/dashboard.insights'
import { Route as DashboardFeesRouteImport } from './routes/dashboard.fees'
import { Route as DashboardFeePlansRouteImport } from './routes/dashboard.fee-plans'
import { Route as DashboardBrandingRouteImport } from './routes/dashboard.branding'
import { Route as DashboardBatchesRouteImport } from './routes/dashboard.batches'
import { Route as DashboardAttendanceRouteImport } from './routes/dashboard.attendance'
import { Route as DashboardAdminsRouteImport } from './routes/dashboard.admins'
import { Route as DashboardAcademyRouteImport } from './routes/dashboard.academy'
import { Route as AcademySlugRouteImport } from './routes/academy.$slug'
import { Route as PlatformAdminTenantsIndexRouteImport } from './routes/platform-admin.tenants.index'
import { Route as MatchCenterTeamsIndexRouteImport } from './routes/match-center.teams.index'
import { Route as MatchCenterPlayersIndexRouteImport } from './routes/match-center.players.index'
import { Route as PlatformAdminTenantsIdRouteImport } from './routes/platform-admin.tenants.$id'
import { Route as MatchCenterTournamentsTournamentIdRouteImport } from './routes/match-center.tournaments.$tournamentId'
import { Route as MatchCenterTeamsNewRouteImport } from './routes/match-center.teams.new'
import { Route as MatchCenterTeamsTeamIdRouteImport } from './routes/match-center.teams.$teamId'
import { Route as MatchCenterScorebookMatchIdRouteImport } from './routes/match-center.scorebook.$matchId'
import { Route as MatchCenterPlayersAthleteIdRouteImport } from './routes/match-center.players.$athleteId'
import { Route as MatchCenterPerformanceCompareRouteImport } from './routes/match-center.performance.compare'
import { Route as MatchCenterPerformanceAthleteIdRouteImport } from './routes/match-center.performance.$athleteId'
import { Route as DashboardStudentsIdRouteImport } from './routes/dashboard.students.$id'
import { Route as ApiPublicManifestWebmanifestRouteImport } from './routes/api/public/manifest.webmanifest'
import { Route as ApiPublicHooksFeeRemindersRouteImport } from './routes/api/public/hooks/fee-reminders'

const StarPlayersRoute = StarPlayersRouteImport.update({
  id: '/star-players',
  path: '/star-players',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformAdminRoute = PlatformAdminRouteImport.update({
  id: '/platform-admin',
  path: '/platform-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentPortalRoute = ParentPortalRouteImport.update({
  id: '/parent-portal',
  path: '/parent-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchCenterRoute = MatchCenterRouteImport.update({
  id: '/match-center',
  path: '/match-center',
  getParentRoute: () => rootRouteImport,
} as any)
const FeesRoute = FeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLaunchRoute = AppLaunchRouteImport.update({
  id: '/app-launch',
  path: '/app-launch',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformAdminIndexRoute = PlatformAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlatformAdminRoute,
} as any)
const MatchCenterIndexRoute = MatchCenterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MatchCenterRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const ScorerMatchIdRoute = ScorerMatchIdRouteImport.update({
  id: '/scorer/$matchId',
  path: '/scorer/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformAdminSubscriptionsRoute =
  PlatformAdminSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => PlatformAdminRoute,
  } as any)
const PlatformAdminSettingsRoute = PlatformAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PlatformAdminRoute,
} as any)
const PlatformAdminNewRoute = PlatformAdminNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PlatformAdminRoute,
} as any)
const MatchSlugRoute = MatchSlugRouteImport.update({
  id: '/match/$slug',
  path: '/match/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchCenterWebsiteRoute = MatchCenterWebsiteRouteImport.update({
  id: '/website',
  path: '/website',
  getParentRoute: () => MatchCenterRoute,
} as any)
const MatchCenterTournamentsRoute = MatchCenterTournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => MatchCenterRoute,
} as any)
const MatchCenterSettingsRoute = MatchCenterSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MatchCenterRoute,
} as any)
const MatchCenterScorersRoute = MatchCenterScorersRouteImport.update({
  id: '/scorers',
  path: '/scorers',
  getParentRoute: () => MatchCenterRoute,
} as any)
const MatchCenterRecordsRoute = MatchCenterRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => MatchCenterRoute,
} as any)
const MatchCenterRecognitionRoute = MatchCenterRecognitionRouteImport.update({
  id: '/recognition',
  path: '/recognition',
  getParentRoute: () => MatchCenterRoute,
} as any)
const MatchCenterProfileRoute = MatchCenterProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MatchCenterRoute,
} as any)
const MatchCenterPerformanceRoute = MatchCenterPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => MatchCenterRoute,
} as any)
const MatchCenterMatchesRoute = MatchCenterMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => MatchCenterRoute,
} as any)
const MatchCenterLiveRoute = MatchCenterLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => MatchCenterRoute,
} as any)
const MatchCenterLeaderboardsRoute = MatchCenterLeaderboardsRouteImport.update({
  id: '/leaderboards',
  path: '/leaderboards',
  getParentRoute: () => MatchCenterRoute,
} as any)
const MatchCenterInsightsRoute = MatchCenterInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => MatchCenterRoute,
} as any)
const MatchCenterDashboardRoute = MatchCenterDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => MatchCenterRoute,
} as any)
const MatchCenterCreateRoute = MatchCenterCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => MatchCenterRoute,
} as any)
const MatchCenterAwardsRoute = MatchCenterAwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => MatchCenterRoute,
} as any)
const MatchCenterAiInsightsRoute = MatchCenterAiInsightsRouteImport.update({
  id: '/ai-insights',
  path: '/ai-insights',
  getParentRoute: () => MatchCenterRoute,
} as any)
const MSlugRoute = MSlugRouteImport.update({
  id: '/m/$slug',
  path: '/m/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSubscriptionRoute = DashboardSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStudentsRoute = DashboardStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSiteRoute = DashboardSiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRemindersRoute = DashboardRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRegistrationsRoute = DashboardRegistrationsRouteImport.update({
  id: '/registrations',
  path: '/registrations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLeadsRoute = DashboardLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInsightsRoute = DashboardInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFeesRoute = DashboardFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFeePlansRoute = DashboardFeePlansRouteImport.update({
  id: '/fee-plans',
  path: '/fee-plans',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBrandingRoute = DashboardBrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBatchesRoute = DashboardBatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAttendanceRoute = DashboardAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminsRoute = DashboardAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAcademyRoute = DashboardAcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => DashboardRoute,
} as any)
const AcademySlugRoute = AcademySlugRouteImport.update({
  id: '/academy/$slug',
  path: '/academy/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformAdminTenantsIndexRoute =
  PlatformAdminTenantsIndexRouteImport.update({
    id: '/tenants/',
    path: '/tenants/',
    getParentRoute: () => PlatformAdminRoute,
  } as any)
const MatchCenterTeamsIndexRoute = MatchCenterTeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => MatchCenterRoute,
} as any)
const MatchCenterPlayersIndexRoute = MatchCenterPlayersIndexRouteImport.update({
  id: '/players/',
  path: '/players/',
  getParentRoute: () => MatchCenterRoute,
} as any)
const PlatformAdminTenantsIdRoute = PlatformAdminTenantsIdRouteImport.update({
  id: '/tenants/$id',
  path: '/tenants/$id',
  getParentRoute: () => PlatformAdminRoute,
} as any)
const MatchCenterTournamentsTournamentIdRoute =
  MatchCenterTournamentsTournamentIdRouteImport.update({
    id: '/$tournamentId',
    path: '/$tournamentId',
    getParentRoute: () => MatchCenterTournamentsRoute,
  } as any)
const MatchCenterTeamsNewRoute = MatchCenterTeamsNewRouteImport.update({
  id: '/teams/new',
  path: '/teams/new',
  getParentRoute: () => MatchCenterRoute,
} as any)
const MatchCenterTeamsTeamIdRoute = MatchCenterTeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => MatchCenterRoute,
} as any)
const MatchCenterScorebookMatchIdRoute =
  MatchCenterScorebookMatchIdRouteImport.update({
    id: '/scorebook/$matchId',
    path: '/scorebook/$matchId',
    getParentRoute: () => MatchCenterRoute,
  } as any)
const MatchCenterPlayersAthleteIdRoute =
  MatchCenterPlayersAthleteIdRouteImport.update({
    id: '/players/$athleteId',
    path: '/players/$athleteId',
    getParentRoute: () => MatchCenterRoute,
  } as any)
const MatchCenterPerformanceCompareRoute =
  MatchCenterPerformanceCompareRouteImport.update({
    id: '/compare',
    path: '/compare',
    getParentRoute: () => MatchCenterPerformanceRoute,
  } as any)
const MatchCenterPerformanceAthleteIdRoute =
  MatchCenterPerformanceAthleteIdRouteImport.update({
    id: '/$athleteId',
    path: '/$athleteId',
    getParentRoute: () => MatchCenterPerformanceRoute,
  } as any)
const DashboardStudentsIdRoute = DashboardStudentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardStudentsRoute,
} as any)
const ApiPublicManifestWebmanifestRoute =
  ApiPublicManifestWebmanifestRouteImport.update({
    id: '/api/public/manifest/webmanifest',
    path: '/api/public/manifest/webmanifest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksFeeRemindersRoute =
  ApiPublicHooksFeeRemindersRouteImport.update({
    id: '/api/public/hooks/fee-reminders',
    path: '/api/public/hooks/fee-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app-launch': typeof AppLaunchRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/fees': typeof FeesRoute
  '/match-center': typeof MatchCenterRouteWithChildren
  '/parent-portal': typeof ParentPortalRoute
  '/platform-admin': typeof PlatformAdminRouteWithChildren
  '/register': typeof RegisterRoute
  '/star-players': typeof StarPlayersRoute
  '/academy/$slug': typeof AcademySlugRoute
  '/dashboard/academy': typeof DashboardAcademyRoute
  '/dashboard/admins': typeof DashboardAdminsRoute
  '/dashboard/attendance': typeof DashboardAttendanceRoute
  '/dashboard/batches': typeof DashboardBatchesRoute
  '/dashboard/branding': typeof DashboardBrandingRoute
  '/dashboard/fee-plans': typeof DashboardFeePlansRoute
  '/dashboard/fees': typeof DashboardFeesRoute
  '/dashboard/insights': typeof DashboardInsightsRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/registrations': typeof DashboardRegistrationsRoute
  '/dashboard/reminders': typeof DashboardRemindersRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/site': typeof DashboardSiteRoute
  '/dashboard/students': typeof DashboardStudentsRouteWithChildren
  '/dashboard/subscription': typeof DashboardSubscriptionRoute
  '/m/$slug': typeof MSlugRoute
  '/match-center/ai-insights': typeof MatchCenterAiInsightsRoute
  '/match-center/awards': typeof MatchCenterAwardsRoute
  '/match-center/create': typeof MatchCenterCreateRoute
  '/match-center/dashboard': typeof MatchCenterDashboardRoute
  '/match-center/insights': typeof MatchCenterInsightsRoute
  '/match-center/leaderboards': typeof MatchCenterLeaderboardsRoute
  '/match-center/live': typeof MatchCenterLiveRoute
  '/match-center/matches': typeof MatchCenterMatchesRoute
  '/match-center/performance': typeof MatchCenterPerformanceRouteWithChildren
  '/match-center/profile': typeof MatchCenterProfileRoute
  '/match-center/recognition': typeof MatchCenterRecognitionRoute
  '/match-center/records': typeof MatchCenterRecordsRoute
  '/match-center/scorers': typeof MatchCenterScorersRoute
  '/match-center/settings': typeof MatchCenterSettingsRoute
  '/match-center/tournaments': typeof MatchCenterTournamentsRouteWithChildren
  '/match-center/website': typeof MatchCenterWebsiteRoute
  '/match/$slug': typeof MatchSlugRoute
  '/platform-admin/new': typeof PlatformAdminNewRoute
  '/platform-admin/settings': typeof PlatformAdminSettingsRoute
  '/platform-admin/subscriptions': typeof PlatformAdminSubscriptionsRoute
  '/scorer/$matchId': typeof ScorerMatchIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/match-center/': typeof MatchCenterIndexRoute
  '/platform-admin/': typeof PlatformAdminIndexRoute
  '/dashboard/students/$id': typeof DashboardStudentsIdRoute
  '/match-center/performance/$athleteId': typeof MatchCenterPerformanceAthleteIdRoute
  '/match-center/performance/compare': typeof MatchCenterPerformanceCompareRoute
  '/match-center/players/$athleteId': typeof MatchCenterPlayersAthleteIdRoute
  '/match-center/scorebook/$matchId': typeof MatchCenterScorebookMatchIdRoute
  '/match-center/teams/$teamId': typeof MatchCenterTeamsTeamIdRoute
  '/match-center/teams/new': typeof MatchCenterTeamsNewRoute
  '/match-center/tournaments/$tournamentId': typeof MatchCenterTournamentsTournamentIdRoute
  '/platform-admin/tenants/$id': typeof PlatformAdminTenantsIdRoute
  '/match-center/players/': typeof MatchCenterPlayersIndexRoute
  '/match-center/teams/': typeof MatchCenterTeamsIndexRoute
  '/platform-admin/tenants/': typeof PlatformAdminTenantsIndexRoute
  '/api/public/hooks/fee-reminders': typeof ApiPublicHooksFeeRemindersRoute
  '/api/public/manifest/webmanifest': typeof ApiPublicManifestWebmanifestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app-launch': typeof AppLaunchRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/fees': typeof FeesRoute
  '/parent-portal': typeof ParentPortalRoute
  '/register': typeof RegisterRoute
  '/star-players': typeof StarPlayersRoute
  '/academy/$slug': typeof AcademySlugRoute
  '/dashboard/academy': typeof DashboardAcademyRoute
  '/dashboard/admins': typeof DashboardAdminsRoute
  '/dashboard/attendance': typeof DashboardAttendanceRoute
  '/dashboard/batches': typeof DashboardBatchesRoute
  '/dashboard/branding': typeof DashboardBrandingRoute
  '/dashboard/fee-plans': typeof DashboardFeePlansRoute
  '/dashboard/fees': typeof DashboardFeesRoute
  '/dashboard/insights': typeof DashboardInsightsRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/registrations': typeof DashboardRegistrationsRoute
  '/dashboard/reminders': typeof DashboardRemindersRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/site': typeof DashboardSiteRoute
  '/dashboard/students': typeof DashboardStudentsRouteWithChildren
  '/dashboard/subscription': typeof DashboardSubscriptionRoute
  '/m/$slug': typeof MSlugRoute
  '/match-center/ai-insights': typeof MatchCenterAiInsightsRoute
  '/match-center/awards': typeof MatchCenterAwardsRoute
  '/match-center/create': typeof MatchCenterCreateRoute
  '/match-center/dashboard': typeof MatchCenterDashboardRoute
  '/match-center/insights': typeof MatchCenterInsightsRoute
  '/match-center/leaderboards': typeof MatchCenterLeaderboardsRoute
  '/match-center/live': typeof MatchCenterLiveRoute
  '/match-center/matches': typeof MatchCenterMatchesRoute
  '/match-center/performance': typeof MatchCenterPerformanceRouteWithChildren
  '/match-center/profile': typeof MatchCenterProfileRoute
  '/match-center/recognition': typeof MatchCenterRecognitionRoute
  '/match-center/records': typeof MatchCenterRecordsRoute
  '/match-center/scorers': typeof MatchCenterScorersRoute
  '/match-center/settings': typeof MatchCenterSettingsRoute
  '/match-center/tournaments': typeof MatchCenterTournamentsRouteWithChildren
  '/match-center/website': typeof MatchCenterWebsiteRoute
  '/match/$slug': typeof MatchSlugRoute
  '/platform-admin/new': typeof PlatformAdminNewRoute
  '/platform-admin/settings': typeof PlatformAdminSettingsRoute
  '/platform-admin/subscriptions': typeof PlatformAdminSubscriptionsRoute
  '/scorer/$matchId': typeof ScorerMatchIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/match-center': typeof MatchCenterIndexRoute
  '/platform-admin': typeof PlatformAdminIndexRoute
  '/dashboard/students/$id': typeof DashboardStudentsIdRoute
  '/match-center/performance/$athleteId': typeof MatchCenterPerformanceAthleteIdRoute
  '/match-center/performance/compare': typeof MatchCenterPerformanceCompareRoute
  '/match-center/players/$athleteId': typeof MatchCenterPlayersAthleteIdRoute
  '/match-center/scorebook/$matchId': typeof MatchCenterScorebookMatchIdRoute
  '/match-center/teams/$teamId': typeof MatchCenterTeamsTeamIdRoute
  '/match-center/teams/new': typeof MatchCenterTeamsNewRoute
  '/match-center/tournaments/$tournamentId': typeof MatchCenterTournamentsTournamentIdRoute
  '/platform-admin/tenants/$id': typeof PlatformAdminTenantsIdRoute
  '/match-center/players': typeof MatchCenterPlayersIndexRoute
  '/match-center/teams': typeof MatchCenterTeamsIndexRoute
  '/platform-admin/tenants': typeof PlatformAdminTenantsIndexRoute
  '/api/public/hooks/fee-reminders': typeof ApiPublicHooksFeeRemindersRoute
  '/api/public/manifest/webmanifest': typeof ApiPublicManifestWebmanifestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app-launch': typeof AppLaunchRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/fees': typeof FeesRoute
  '/match-center': typeof MatchCenterRouteWithChildren
  '/parent-portal': typeof ParentPortalRoute
  '/platform-admin': typeof PlatformAdminRouteWithChildren
  '/register': typeof RegisterRoute
  '/star-players': typeof StarPlayersRoute
  '/academy/$slug': typeof AcademySlugRoute
  '/dashboard/academy': typeof DashboardAcademyRoute
  '/dashboard/admins': typeof DashboardAdminsRoute
  '/dashboard/attendance': typeof DashboardAttendanceRoute
  '/dashboard/batches': typeof DashboardBatchesRoute
  '/dashboard/branding': typeof DashboardBrandingRoute
  '/dashboard/fee-plans': typeof DashboardFeePlansRoute
  '/dashboard/fees': typeof DashboardFeesRoute
  '/dashboard/insights': typeof DashboardInsightsRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/registrations': typeof DashboardRegistrationsRoute
  '/dashboard/reminders': typeof DashboardRemindersRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/site': typeof DashboardSiteRoute
  '/dashboard/students': typeof DashboardStudentsRouteWithChildren
  '/dashboard/subscription': typeof DashboardSubscriptionRoute
  '/m/$slug': typeof MSlugRoute
  '/match-center/ai-insights': typeof MatchCenterAiInsightsRoute
  '/match-center/awards': typeof MatchCenterAwardsRoute
  '/match-center/create': typeof MatchCenterCreateRoute
  '/match-center/dashboard': typeof MatchCenterDashboardRoute
  '/match-center/insights': typeof MatchCenterInsightsRoute
  '/match-center/leaderboards': typeof MatchCenterLeaderboardsRoute
  '/match-center/live': typeof MatchCenterLiveRoute
  '/match-center/matches': typeof MatchCenterMatchesRoute
  '/match-center/performance': typeof MatchCenterPerformanceRouteWithChildren
  '/match-center/profile': typeof MatchCenterProfileRoute
  '/match-center/recognition': typeof MatchCenterRecognitionRoute
  '/match-center/records': typeof MatchCenterRecordsRoute
  '/match-center/scorers': typeof MatchCenterScorersRoute
  '/match-center/settings': typeof MatchCenterSettingsRoute
  '/match-center/tournaments': typeof MatchCenterTournamentsRouteWithChildren
  '/match-center/website': typeof MatchCenterWebsiteRoute
  '/match/$slug': typeof MatchSlugRoute
  '/platform-admin/new': typeof PlatformAdminNewRoute
  '/platform-admin/settings': typeof PlatformAdminSettingsRoute
  '/platform-admin/subscriptions': typeof PlatformAdminSubscriptionsRoute
  '/scorer/$matchId': typeof ScorerMatchIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/match-center/': typeof MatchCenterIndexRoute
  '/platform-admin/': typeof PlatformAdminIndexRoute
  '/dashboard/students/$id': typeof DashboardStudentsIdRoute
  '/match-center/performance/$athleteId': typeof MatchCenterPerformanceAthleteIdRoute
  '/match-center/performance/compare': typeof MatchCenterPerformanceCompareRoute
  '/match-center/players/$athleteId': typeof MatchCenterPlayersAthleteIdRoute
  '/match-center/scorebook/$matchId': typeof MatchCenterScorebookMatchIdRoute
  '/match-center/teams/$teamId': typeof MatchCenterTeamsTeamIdRoute
  '/match-center/teams/new': typeof MatchCenterTeamsNewRoute
  '/match-center/tournaments/$tournamentId': typeof MatchCenterTournamentsTournamentIdRoute
  '/platform-admin/tenants/$id': typeof PlatformAdminTenantsIdRoute
  '/match-center/players/': typeof MatchCenterPlayersIndexRoute
  '/match-center/teams/': typeof MatchCenterTeamsIndexRoute
  '/platform-admin/tenants/': typeof PlatformAdminTenantsIndexRoute
  '/api/public/hooks/fee-reminders': typeof ApiPublicHooksFeeRemindersRoute
  '/api/public/manifest/webmanifest': typeof ApiPublicManifestWebmanifestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app-launch'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/fees'
    | '/match-center'
    | '/parent-portal'
    | '/platform-admin'
    | '/register'
    | '/star-players'
    | '/academy/$slug'
    | '/dashboard/academy'
    | '/dashboard/admins'
    | '/dashboard/attendance'
    | '/dashboard/batches'
    | '/dashboard/branding'
    | '/dashboard/fee-plans'
    | '/dashboard/fees'
    | '/dashboard/insights'
    | '/dashboard/leads'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/dashboard/registrations'
    | '/dashboard/reminders'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/site'
    | '/dashboard/students'
    | '/dashboard/subscription'
    | '/m/$slug'
    | '/match-center/ai-insights'
    | '/match-center/awards'
    | '/match-center/create'
    | '/match-center/dashboard'
    | '/match-center/insights'
    | '/match-center/leaderboards'
    | '/match-center/live'
    | '/match-center/matches'
    | '/match-center/performance'
    | '/match-center/profile'
    | '/match-center/recognition'
    | '/match-center/records'
    | '/match-center/scorers'
    | '/match-center/settings'
    | '/match-center/tournaments'
    | '/match-center/website'
    | '/match/$slug'
    | '/platform-admin/new'
    | '/platform-admin/settings'
    | '/platform-admin/subscriptions'
    | '/scorer/$matchId'
    | '/dashboard/'
    | '/match-center/'
    | '/platform-admin/'
    | '/dashboard/students/$id'
    | '/match-center/performance/$athleteId'
    | '/match-center/performance/compare'
    | '/match-center/players/$athleteId'
    | '/match-center/scorebook/$matchId'
    | '/match-center/teams/$teamId'
    | '/match-center/teams/new'
    | '/match-center/tournaments/$tournamentId'
    | '/platform-admin/tenants/$id'
    | '/match-center/players/'
    | '/match-center/teams/'
    | '/platform-admin/tenants/'
    | '/api/public/hooks/fee-reminders'
    | '/api/public/manifest/webmanifest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/app-launch'
    | '/auth'
    | '/contact'
    | '/fees'
    | '/parent-portal'
    | '/register'
    | '/star-players'
    | '/academy/$slug'
    | '/dashboard/academy'
    | '/dashboard/admins'
    | '/dashboard/attendance'
    | '/dashboard/batches'
    | '/dashboard/branding'
    | '/dashboard/fee-plans'
    | '/dashboard/fees'
    | '/dashboard/insights'
    | '/dashboard/leads'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/dashboard/registrations'
    | '/dashboard/reminders'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/site'
    | '/dashboard/students'
    | '/dashboard/subscription'
    | '/m/$slug'
    | '/match-center/ai-insights'
    | '/match-center/awards'
    | '/match-center/create'
    | '/match-center/dashboard'
    | '/match-center/insights'
    | '/match-center/leaderboards'
    | '/match-center/live'
    | '/match-center/matches'
    | '/match-center/performance'
    | '/match-center/profile'
    | '/match-center/recognition'
    | '/match-center/records'
    | '/match-center/scorers'
    | '/match-center/settings'
    | '/match-center/tournaments'
    | '/match-center/website'
    | '/match/$slug'
    | '/platform-admin/new'
    | '/platform-admin/settings'
    | '/platform-admin/subscriptions'
    | '/scorer/$matchId'
    | '/dashboard'
    | '/match-center'
    | '/platform-admin'
    | '/dashboard/students/$id'
    | '/match-center/performance/$athleteId'
    | '/match-center/performance/compare'
    | '/match-center/players/$athleteId'
    | '/match-center/scorebook/$matchId'
    | '/match-center/teams/$teamId'
    | '/match-center/teams/new'
    | '/match-center/tournaments/$tournamentId'
    | '/platform-admin/tenants/$id'
    | '/match-center/players'
    | '/match-center/teams'
    | '/platform-admin/tenants'
    | '/api/public/hooks/fee-reminders'
    | '/api/public/manifest/webmanifest'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app-launch'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/fees'
    | '/match-center'
    | '/parent-portal'
    | '/platform-admin'
    | '/register'
    | '/star-players'
    | '/academy/$slug'
    | '/dashboard/academy'
    | '/dashboard/admins'
    | '/dashboard/attendance'
    | '/dashboard/batches'
    | '/dashboard/branding'
    | '/dashboard/fee-plans'
    | '/dashboard/fees'
    | '/dashboard/insights'
    | '/dashboard/leads'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/dashboard/registrations'
    | '/dashboard/reminders'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/site'
    | '/dashboard/students'
    | '/dashboard/subscription'
    | '/m/$slug'
    | '/match-center/ai-insights'
    | '/match-center/awards'
    | '/match-center/create'
    | '/match-center/dashboard'
    | '/match-center/insights'
    | '/match-center/leaderboards'
    | '/match-center/live'
    | '/match-center/matches'
    | '/match-center/performance'
    | '/match-center/profile'
    | '/match-center/recognition'
    | '/match-center/records'
    | '/match-center/scorers'
    | '/match-center/settings'
    | '/match-center/tournaments'
    | '/match-center/website'
    | '/match/$slug'
    | '/platform-admin/new'
    | '/platform-admin/settings'
    | '/platform-admin/subscriptions'
    | '/scorer/$matchId'
    | '/dashboard/'
    | '/match-center/'
    | '/platform-admin/'
    | '/dashboard/students/$id'
    | '/match-center/performance/$athleteId'
    | '/match-center/performance/compare'
    | '/match-center/players/$athleteId'
    | '/match-center/scorebook/$matchId'
    | '/match-center/teams/$teamId'
    | '/match-center/teams/new'
    | '/match-center/tournaments/$tournamentId'
    | '/platform-admin/tenants/$id'
    | '/match-center/players/'
    | '/match-center/teams/'
    | '/platform-admin/tenants/'
    | '/api/public/hooks/fee-reminders'
    | '/api/public/manifest/webmanifest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppLaunchRoute: typeof AppLaunchRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  FeesRoute: typeof FeesRoute
  MatchCenterRoute: typeof MatchCenterRouteWithChildren
  ParentPortalRoute: typeof ParentPortalRoute
  PlatformAdminRoute: typeof PlatformAdminRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  StarPlayersRoute: typeof StarPlayersRoute
  AcademySlugRoute: typeof AcademySlugRoute
  MSlugRoute: typeof MSlugRoute
  MatchSlugRoute: typeof MatchSlugRoute
  ScorerMatchIdRoute: typeof ScorerMatchIdRoute
  ApiPublicHooksFeeRemindersRoute: typeof ApiPublicHooksFeeRemindersRoute
  ApiPublicManifestWebmanifestRoute: typeof ApiPublicManifestWebmanifestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/star-players': {
      id: '/star-players'
      path: '/star-players'
      fullPath: '/star-players'
      preLoaderRoute: typeof StarPlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform-admin': {
      id: '/platform-admin'
      path: '/platform-admin'
      fullPath: '/platform-admin'
      preLoaderRoute: typeof PlatformAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent-portal': {
      id: '/parent-portal'
      path: '/parent-portal'
      fullPath: '/parent-portal'
      preLoaderRoute: typeof ParentPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match-center': {
      id: '/match-center'
      path: '/match-center'
      fullPath: '/match-center'
      preLoaderRoute: typeof MatchCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fees': {
      id: '/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof FeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app-launch': {
      id: '/app-launch'
      path: '/app-launch'
      fullPath: '/app-launch'
      preLoaderRoute: typeof AppLaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform-admin/': {
      id: '/platform-admin/'
      path: '/'
      fullPath: '/platform-admin/'
      preLoaderRoute: typeof PlatformAdminIndexRouteImport
      parentRoute: typeof PlatformAdminRoute
    }
    '/match-center/': {
      id: '/match-center/'
      path: '/'
      fullPath: '/match-center/'
      preLoaderRoute: typeof MatchCenterIndexRouteImport
      parentRoute: typeof MatchCenterRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/scorer/$matchId': {
      id: '/scorer/$matchId'
      path: '/scorer/$matchId'
      fullPath: '/scorer/$matchId'
      preLoaderRoute: typeof ScorerMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform-admin/subscriptions': {
      id: '/platform-admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/platform-admin/subscriptions'
      preLoaderRoute: typeof PlatformAdminSubscriptionsRouteImport
      parentRoute: typeof PlatformAdminRoute
    }
    '/platform-admin/settings': {
      id: '/platform-admin/settings'
      path: '/settings'
      fullPath: '/platform-admin/settings'
      preLoaderRoute: typeof PlatformAdminSettingsRouteImport
      parentRoute: typeof PlatformAdminRoute
    }
    '/platform-admin/new': {
      id: '/platform-admin/new'
      path: '/new'
      fullPath: '/platform-admin/new'
      preLoaderRoute: typeof PlatformAdminNewRouteImport
      parentRoute: typeof PlatformAdminRoute
    }
    '/match/$slug': {
      id: '/match/$slug'
      path: '/match/$slug'
      fullPath: '/match/$slug'
      preLoaderRoute: typeof MatchSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match-center/website': {
      id: '/match-center/website'
      path: '/website'
      fullPath: '/match-center/website'
      preLoaderRoute: typeof MatchCenterWebsiteRouteImport
      parentRoute: typeof MatchCenterRoute
    }
    '/match-center/tournaments': {
      id: '/match-center/tournaments'
      path: '/tournaments'
      fullPath: '/match-center/tournaments'
      preLoaderRoute: typeof MatchCenterTournamentsRouteImport
      parentRoute: typeof MatchCenterRoute
    }
    '/match-center/settings': {
      id: '/match-center/settings'
      path: '/settings'
      fullPath: '/match-center/settings'
      preLoaderRoute: typeof MatchCenterSettingsRouteImport
      parentRoute: typeof MatchCenterRoute
    }
    '/match-center/scorers': {
      id: '/match-center/scorers'
      path: '/scorers'
      fullPath: '/match-center/scorers'
      preLoaderRoute: typeof MatchCenterScorersRouteImport
      parentRoute: typeof MatchCenterRoute
    }
    '/match-center/records': {
      id: '/match-center/records'
      path: '/records'
      fullPath: '/match-center/records'
      preLoaderRoute: typeof MatchCenterRecordsRouteImport
      parentRoute: typeof MatchCenterRoute
    }
    '/match-center/recognition': {
      id: '/match-center/recognition'
      path: '/recognition'
      fullPath: '/match-center/recognition'
      preLoaderRoute: typeof MatchCenterRecognitionRouteImport
      parentRoute: typeof MatchCenterRoute
    }
    '/match-center/profile': {
      id: '/match-center/profile'
      path: '/profile'
      fullPath: '/match-center/profile'
      preLoaderRoute: typeof MatchCenterProfileRouteImport
      parentRoute: typeof MatchCenterRoute
    }
    '/match-center/performance': {
      id: '/match-center/performance'
      path: '/performance'
      fullPath: '/match-center/performance'
      preLoaderRoute: typeof MatchCenterPerformanceRouteImport
      parentRoute: typeof MatchCenterRoute
    }
    '/match-center/matches': {
      id: '/match-center/matches'
      path: '/matches'
      fullPath: '/match-center/matches'
      preLoaderRoute: typeof MatchCenterMatchesRouteImport
      parentRoute: typeof MatchCenterRoute
    }
    '/match-center/live': {
      id: '/match-center/live'
      path: '/live'
      fullPath: '/match-center/live'
      preLoaderRoute: typeof MatchCenterLiveRouteImport
      parentRoute: typeof MatchCenterRoute
    }
    '/match-center/leaderboards': {
      id: '/match-center/leaderboards'
      path: '/leaderboards'
      fullPath: '/match-center/leaderboards'
      preLoaderRoute: typeof MatchCenterLeaderboardsRouteImport
      parentRoute: typeof MatchCenterRoute
    }
    '/match-center/insights': {
      id: '/match-center/insights'
      path: '/insights'
      fullPath: '/match-center/insights'
      preLoaderRoute: typeof MatchCenterInsightsRouteImport
      parentRoute: typeof MatchCenterRoute
    }
    '/match-center/dashboard': {
      id: '/match-center/dashboard'
      path: '/dashboard'
      fullPath: '/match-center/dashboard'
      preLoaderRoute: typeof MatchCenterDashboardRouteImport
      parentRoute: typeof MatchCenterRoute
    }
    '/match-center/create': {
      id: '/match-center/create'
      path: '/create'
      fullPath: '/match-center/create'
      preLoaderRoute: typeof MatchCenterCreateRouteImport
      parentRoute: typeof MatchCenterRoute
    }
    '/match-center/awards': {
      id: '/match-center/awards'
      path: '/awards'
      fullPath: '/match-center/awards'
      preLoaderRoute: typeof MatchCenterAwardsRouteImport
      parentRoute: typeof MatchCenterRoute
    }
    '/match-center/ai-insights': {
      id: '/match-center/ai-insights'
      path: '/ai-insights'
      fullPath: '/match-center/ai-insights'
      preLoaderRoute: typeof MatchCenterAiInsightsRouteImport
      parentRoute: typeof MatchCenterRoute
    }
    '/m/$slug': {
      id: '/m/$slug'
      path: '/m/$slug'
      fullPath: '/m/$slug'
      preLoaderRoute: typeof MSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/subscription': {
      id: '/dashboard/subscription'
      path: '/subscription'
      fullPath: '/dashboard/subscription'
      preLoaderRoute: typeof DashboardSubscriptionRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/students': {
      id: '/dashboard/students'
      path: '/students'
      fullPath: '/dashboard/students'
      preLoaderRoute: typeof DashboardStudentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/site': {
      id: '/dashboard/site'
      path: '/site'
      fullPath: '/dashboard/site'
      preLoaderRoute: typeof DashboardSiteRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reminders': {
      id: '/dashboard/reminders'
      path: '/reminders'
      fullPath: '/dashboard/reminders'
      preLoaderRoute: typeof DashboardRemindersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/registrations': {
      id: '/dashboard/registrations'
      path: '/registrations'
      fullPath: '/dashboard/registrations'
      preLoaderRoute: typeof DashboardRegistrationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/leads': {
      id: '/dashboard/leads'
      path: '/leads'
      fullPath: '/dashboard/leads'
      preLoaderRoute: typeof DashboardLeadsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/insights': {
      id: '/dashboard/insights'
      path: '/insights'
      fullPath: '/dashboard/insights'
      preLoaderRoute: typeof DashboardInsightsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/fees': {
      id: '/dashboard/fees'
      path: '/fees'
      fullPath: '/dashboard/fees'
      preLoaderRoute: typeof DashboardFeesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/fee-plans': {
      id: '/dashboard/fee-plans'
      path: '/fee-plans'
      fullPath: '/dashboard/fee-plans'
      preLoaderRoute: typeof DashboardFeePlansRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/branding': {
      id: '/dashboard/branding'
      path: '/branding'
      fullPath: '/dashboard/branding'
      preLoaderRoute: typeof DashboardBrandingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/batches': {
      id: '/dashboard/batches'
      path: '/batches'
      fullPath: '/dashboard/batches'
      preLoaderRoute: typeof DashboardBatchesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/attendance': {
      id: '/dashboard/attendance'
      path: '/attendance'
      fullPath: '/dashboard/attendance'
      preLoaderRoute: typeof DashboardAttendanceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admins': {
      id: '/dashboard/admins'
      path: '/admins'
      fullPath: '/dashboard/admins'
      preLoaderRoute: typeof DashboardAdminsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/academy': {
      id: '/dashboard/academy'
      path: '/academy'
      fullPath: '/dashboard/academy'
      preLoaderRoute: typeof DashboardAcademyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/academy/$slug': {
      id: '/academy/$slug'
      path: '/academy/$slug'
      fullPath: '/academy/$slug'
      preLoaderRoute: typeof AcademySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform-admin/tenants/': {
      id: '/platform-admin/tenants/'
      path: '/tenants'
      fullPath: '/platform-admin/tenants/'
      preLoaderRoute: typeof PlatformAdminTenantsIndexRouteImport
      parentRoute: typeof PlatformAdminRoute
    }
    '/match-center/teams/': {
      id: '/match-center/teams/'
      path: '/teams'
      fullPath: '/match-center/teams/'
      preLoaderRoute: typeof MatchCenterTeamsIndexRouteImport
      parentRoute: typeof MatchCenterRoute
    }
    '/match-center/players/': {
      id: '/match-center/players/'
      path: '/players'
      fullPath: '/match-center/players/'
      preLoaderRoute: typeof MatchCenterPlayersIndexRouteImport
      parentRoute: typeof MatchCenterRoute
    }
    '/platform-admin/tenants/$id': {
      id: '/platform-admin/tenants/$id'
      path: '/tenants/$id'
      fullPath: '/platform-admin/tenants/$id'
      preLoaderRoute: typeof PlatformAdminTenantsIdRouteImport
      parentRoute: typeof PlatformAdminRoute
    }
    '/match-center/tournaments/$tournamentId': {
      id: '/match-center/tournaments/$tournamentId'
      path: '/$tournamentId'
      fullPath: '/match-center/tournaments/$tournamentId'
      preLoaderRoute: typeof MatchCenterTournamentsTournamentIdRouteImport
      parentRoute: typeof MatchCenterTournamentsRoute
    }
    '/match-center/teams/new': {
      id: '/match-center/teams/new'
      path: '/teams/new'
      fullPath: '/match-center/teams/new'
      preLoaderRoute: typeof MatchCenterTeamsNewRouteImport
      parentRoute: typeof MatchCenterRoute
    }
    '/match-center/teams/$teamId': {
      id: '/match-center/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/match-center/teams/$teamId'
      preLoaderRoute: typeof MatchCenterTeamsTeamIdRouteImport
      parentRoute: typeof MatchCenterRoute
    }
    '/match-center/scorebook/$matchId': {
      id: '/match-center/scorebook/$matchId'
      path: '/scorebook/$matchId'
      fullPath: '/match-center/scorebook/$matchId'
      preLoaderRoute: typeof MatchCenterScorebookMatchIdRouteImport
      parentRoute: typeof MatchCenterRoute
    }
    '/match-center/players/$athleteId': {
      id: '/match-center/players/$athleteId'
      path: '/players/$athleteId'
      fullPath: '/match-center/players/$athleteId'
      preLoaderRoute: typeof MatchCenterPlayersAthleteIdRouteImport
      parentRoute: typeof MatchCenterRoute
    }
    '/match-center/performance/compare': {
      id: '/match-center/performance/compare'
      path: '/compare'
      fullPath: '/match-center/performance/compare'
      preLoaderRoute: typeof MatchCenterPerformanceCompareRouteImport
      parentRoute: typeof MatchCenterPerformanceRoute
    }
    '/match-center/performance/$athleteId': {
      id: '/match-center/performance/$athleteId'
      path: '/$athleteId'
      fullPath: '/match-center/performance/$athleteId'
      preLoaderRoute: typeof MatchCenterPerformanceAthleteIdRouteImport
      parentRoute: typeof MatchCenterPerformanceRoute
    }
    '/dashboard/students/$id': {
      id: '/dashboard/students/$id'
      path: '/$id'
      fullPath: '/dashboard/students/$id'
      preLoaderRoute: typeof DashboardStudentsIdRouteImport
      parentRoute: typeof DashboardStudentsRoute
    }
    '/api/public/manifest/webmanifest': {
      id: '/api/public/manifest/webmanifest'
      path: '/api/public/manifest/webmanifest'
      fullPath: '/api/public/manifest/webmanifest'
      preLoaderRoute: typeof ApiPublicManifestWebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/fee-reminders': {
      id: '/api/public/hooks/fee-reminders'
      path: '/api/public/hooks/fee-reminders'
      fullPath: '/api/public/hooks/fee-reminders'
      preLoaderRoute: typeof ApiPublicHooksFeeRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardStudentsRouteChildren {
  DashboardStudentsIdRoute: typeof DashboardStudentsIdRoute
}

const DashboardStudentsRouteChildren: DashboardStudentsRouteChildren = {
  DashboardStudentsIdRoute: DashboardStudentsIdRoute,
}

const DashboardStudentsRouteWithChildren =
  DashboardStudentsRoute._addFileChildren(DashboardStudentsRouteChildren)

interface DashboardRouteChildren {
  DashboardAcademyRoute: typeof DashboardAcademyRoute
  DashboardAdminsRoute: typeof DashboardAdminsRoute
  DashboardAttendanceRoute: typeof DashboardAttendanceRoute
  DashboardBatchesRoute: typeof DashboardBatchesRoute
  DashboardBrandingRoute: typeof DashboardBrandingRoute
  DashboardFeePlansRoute: typeof DashboardFeePlansRoute
  DashboardFeesRoute: typeof DashboardFeesRoute
  DashboardInsightsRoute: typeof DashboardInsightsRoute
  DashboardLeadsRoute: typeof DashboardLeadsRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardRegistrationsRoute: typeof DashboardRegistrationsRoute
  DashboardRemindersRoute: typeof DashboardRemindersRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSiteRoute: typeof DashboardSiteRoute
  DashboardStudentsRoute: typeof DashboardStudentsRouteWithChildren
  DashboardSubscriptionRoute: typeof DashboardSubscriptionRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAcademyRoute: DashboardAcademyRoute,
  DashboardAdminsRoute: DashboardAdminsRoute,
  DashboardAttendanceRoute: DashboardAttendanceRoute,
  DashboardBatchesRoute: DashboardBatchesRoute,
  DashboardBrandingRoute: DashboardBrandingRoute,
  DashboardFeePlansRoute: DashboardFeePlansRoute,
  DashboardFeesRoute: DashboardFeesRoute,
  DashboardInsightsRoute: DashboardInsightsRoute,
  DashboardLeadsRoute: DashboardLeadsRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardRegistrationsRoute: DashboardRegistrationsRoute,
  DashboardRemindersRoute: DashboardRemindersRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSiteRoute: DashboardSiteRoute,
  DashboardStudentsRoute: DashboardStudentsRouteWithChildren,
  DashboardSubscriptionRoute: DashboardSubscriptionRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface MatchCenterPerformanceRouteChildren {
  MatchCenterPerformanceAthleteIdRoute: typeof MatchCenterPerformanceAthleteIdRoute
  MatchCenterPerformanceCompareRoute: typeof MatchCenterPerformanceCompareRoute
}

const MatchCenterPerformanceRouteChildren: MatchCenterPerformanceRouteChildren =
  {
    MatchCenterPerformanceAthleteIdRoute: MatchCenterPerformanceAthleteIdRoute,
    MatchCenterPerformanceCompareRoute: MatchCenterPerformanceCompareRoute,
  }

const MatchCenterPerformanceRouteWithChildren =
  MatchCenterPerformanceRoute._addFileChildren(
    MatchCenterPerformanceRouteChildren,
  )

interface MatchCenterTournamentsRouteChildren {
  MatchCenterTournamentsTournamentIdRoute: typeof MatchCenterTournamentsTournamentIdRoute
}

const MatchCenterTournamentsRouteChildren: MatchCenterTournamentsRouteChildren =
  {
    MatchCenterTournamentsTournamentIdRoute:
      MatchCenterTournamentsTournamentIdRoute,
  }

const MatchCenterTournamentsRouteWithChildren =
  MatchCenterTournamentsRoute._addFileChildren(
    MatchCenterTournamentsRouteChildren,
  )

interface MatchCenterRouteChildren {
  MatchCenterAiInsightsRoute: typeof MatchCenterAiInsightsRoute
  MatchCenterAwardsRoute: typeof MatchCenterAwardsRoute
  MatchCenterCreateRoute: typeof MatchCenterCreateRoute
  MatchCenterDashboardRoute: typeof MatchCenterDashboardRoute
  MatchCenterInsightsRoute: typeof MatchCenterInsightsRoute
  MatchCenterLeaderboardsRoute: typeof MatchCenterLeaderboardsRoute
  MatchCenterLiveRoute: typeof MatchCenterLiveRoute
  MatchCenterMatchesRoute: typeof MatchCenterMatchesRoute
  MatchCenterPerformanceRoute: typeof MatchCenterPerformanceRouteWithChildren
  MatchCenterProfileRoute: typeof MatchCenterProfileRoute
  MatchCenterRecognitionRoute: typeof MatchCenterRecognitionRoute
  MatchCenterRecordsRoute: typeof MatchCenterRecordsRoute
  MatchCenterScorersRoute: typeof MatchCenterScorersRoute
  MatchCenterSettingsRoute: typeof MatchCenterSettingsRoute
  MatchCenterTournamentsRoute: typeof MatchCenterTournamentsRouteWithChildren
  MatchCenterWebsiteRoute: typeof MatchCenterWebsiteRoute
  MatchCenterIndexRoute: typeof MatchCenterIndexRoute
  MatchCenterPlayersAthleteIdRoute: typeof MatchCenterPlayersAthleteIdRoute
  MatchCenterScorebookMatchIdRoute: typeof MatchCenterScorebookMatchIdRoute
  MatchCenterTeamsTeamIdRoute: typeof MatchCenterTeamsTeamIdRoute
  MatchCenterTeamsNewRoute: typeof MatchCenterTeamsNewRoute
  MatchCenterPlayersIndexRoute: typeof MatchCenterPlayersIndexRoute
  MatchCenterTeamsIndexRoute: typeof MatchCenterTeamsIndexRoute
}

const MatchCenterRouteChildren: MatchCenterRouteChildren = {
  MatchCenterAiInsightsRoute: MatchCenterAiInsightsRoute,
  MatchCenterAwardsRoute: MatchCenterAwardsRoute,
  MatchCenterCreateRoute: MatchCenterCreateRoute,
  MatchCenterDashboardRoute: MatchCenterDashboardRoute,
  MatchCenterInsightsRoute: MatchCenterInsightsRoute,
  MatchCenterLeaderboardsRoute: MatchCenterLeaderboardsRoute,
  MatchCenterLiveRoute: MatchCenterLiveRoute,
  MatchCenterMatchesRoute: MatchCenterMatchesRoute,
  MatchCenterPerformanceRoute: MatchCenterPerformanceRouteWithChildren,
  MatchCenterProfileRoute: MatchCenterProfileRoute,
  MatchCenterRecognitionRoute: MatchCenterRecognitionRoute,
  MatchCenterRecordsRoute: MatchCenterRecordsRoute,
  MatchCenterScorersRoute: MatchCenterScorersRoute,
  MatchCenterSettingsRoute: MatchCenterSettingsRoute,
  MatchCenterTournamentsRoute: MatchCenterTournamentsRouteWithChildren,
  MatchCenterWebsiteRoute: MatchCenterWebsiteRoute,
  MatchCenterIndexRoute: MatchCenterIndexRoute,
  MatchCenterPlayersAthleteIdRoute: MatchCenterPlayersAthleteIdRoute,
  MatchCenterScorebookMatchIdRoute: MatchCenterScorebookMatchIdRoute,
  MatchCenterTeamsTeamIdRoute: MatchCenterTeamsTeamIdRoute,
  MatchCenterTeamsNewRoute: MatchCenterTeamsNewRoute,
  MatchCenterPlayersIndexRoute: MatchCenterPlayersIndexRoute,
  MatchCenterTeamsIndexRoute: MatchCenterTeamsIndexRoute,
}

const MatchCenterRouteWithChildren = MatchCenterRoute._addFileChildren(
  MatchCenterRouteChildren,
)

interface PlatformAdminRouteChildren {
  PlatformAdminNewRoute: typeof PlatformAdminNewRoute
  PlatformAdminSettingsRoute: typeof PlatformAdminSettingsRoute
  PlatformAdminSubscriptionsRoute: typeof PlatformAdminSubscriptionsRoute
  PlatformAdminIndexRoute: typeof PlatformAdminIndexRoute
  PlatformAdminTenantsIdRoute: typeof PlatformAdminTenantsIdRoute
  PlatformAdminTenantsIndexRoute: typeof PlatformAdminTenantsIndexRoute
}

const PlatformAdminRouteChildren: PlatformAdminRouteChildren = {
  PlatformAdminNewRoute: PlatformAdminNewRoute,
  PlatformAdminSettingsRoute: PlatformAdminSettingsRoute,
  PlatformAdminSubscriptionsRoute: PlatformAdminSubscriptionsRoute,
  PlatformAdminIndexRoute: PlatformAdminIndexRoute,
  PlatformAdminTenantsIdRoute: PlatformAdminTenantsIdRoute,
  PlatformAdminTenantsIndexRoute: PlatformAdminTenantsIndexRoute,
}

const PlatformAdminRouteWithChildren = PlatformAdminRoute._addFileChildren(
  PlatformAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppLaunchRoute: AppLaunchRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  FeesRoute: FeesRoute,
  MatchCenterRoute: MatchCenterRouteWithChildren,
  ParentPortalRoute: ParentPortalRoute,
  PlatformAdminRoute: PlatformAdminRouteWithChildren,
  RegisterRoute: RegisterRoute,
  StarPlayersRoute: StarPlayersRoute,
  AcademySlugRoute: AcademySlugRoute,
  MSlugRoute: MSlugRoute,
  MatchSlugRoute: MatchSlugRoute,
  ScorerMatchIdRoute: ScorerMatchIdRoute,
  ApiPublicHooksFeeRemindersRoute: ApiPublicHooksFeeRemindersRoute,
  ApiPublicManifestWebmanifestRoute: ApiPublicManifestWebmanifestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
