/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StarPlayersRouteImport } from './routes/star-players'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PlatformAdminRouteImport } from './routes/platform-admin'
import { Route as FeesRouteImport } from './routes/fees'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlatformAdminIndexRouteImport } from './routes/platform-admin.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as PlatformAdminSubscriptionsRouteImport } from './routes/platform-admin.subscriptions'
import { Route as PlatformAdminNewRouteImport } from './routes/platform-admin.new'
import { Route as DashboardStudentsRouteImport } from './routes/dashboard.students'
import { Route as DashboardSiteRouteImport } from './routes/dashboard.site'
import { Route as DashboardReportsRouteImport } from './routes/dashboard.reports'
import { Route as DashboardRegistrationsRouteImport } from './routes/dashboard.registrations'
import { Route as DashboardFeesRouteImport } from './routes/dashboard.fees'
import { Route as DashboardFeePlansRouteImport } from './routes/dashboard.fee-plans'
import { Route as DashboardBatchesRouteImport } from './routes/dashboard.batches'
import { Route as PlatformAdminTenantsIndexRouteImport } from './routes/platform-admin.tenants.index'
import { Route as PlatformAdminTenantsIdRouteImport } from './routes/platform-admin.tenants.$id'
import { Route as DashboardStudentsIdRouteImport } from './routes/dashboard.students.$id'

const StarPlayersRoute = StarPlayersRouteImport.update({
  id: '/star-players',
  path: '/star-players',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformAdminRoute = PlatformAdminRouteImport.update({
  id: '/platform-admin',
  path: '/platform-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const FeesRoute = FeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformAdminIndexRoute = PlatformAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlatformAdminRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const PlatformAdminSubscriptionsRoute =
  PlatformAdminSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => PlatformAdminRoute,
  } as any)
const PlatformAdminNewRoute = PlatformAdminNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PlatformAdminRoute,
} as any)
const DashboardStudentsRoute = DashboardStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSiteRoute = DashboardSiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRegistrationsRoute = DashboardRegistrationsRouteImport.update({
  id: '/registrations',
  path: '/registrations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFeesRoute = DashboardFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFeePlansRoute = DashboardFeePlansRouteImport.update({
  id: '/fee-plans',
  path: '/fee-plans',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBatchesRoute = DashboardBatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => DashboardRoute,
} as any)
const PlatformAdminTenantsIndexRoute =
  PlatformAdminTenantsIndexRouteImport.update({
    id: '/tenants/',
    path: '/tenants/',
    getParentRoute: () => PlatformAdminRoute,
  } as any)
const PlatformAdminTenantsIdRoute = PlatformAdminTenantsIdRouteImport.update({
  id: '/tenants/$id',
  path: '/tenants/$id',
  getParentRoute: () => PlatformAdminRoute,
} as any)
const DashboardStudentsIdRoute = DashboardStudentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardStudentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/fees': typeof FeesRoute
  '/platform-admin': typeof PlatformAdminRouteWithChildren
  '/register': typeof RegisterRoute
  '/star-players': typeof StarPlayersRoute
  '/dashboard/batches': typeof DashboardBatchesRoute
  '/dashboard/fee-plans': typeof DashboardFeePlansRoute
  '/dashboard/fees': typeof DashboardFeesRoute
  '/dashboard/registrations': typeof DashboardRegistrationsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/site': typeof DashboardSiteRoute
  '/dashboard/students': typeof DashboardStudentsRouteWithChildren
  '/platform-admin/new': typeof PlatformAdminNewRoute
  '/platform-admin/subscriptions': typeof PlatformAdminSubscriptionsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/platform-admin/': typeof PlatformAdminIndexRoute
  '/dashboard/students/$id': typeof DashboardStudentsIdRoute
  '/platform-admin/tenants/$id': typeof PlatformAdminTenantsIdRoute
  '/platform-admin/tenants/': typeof PlatformAdminTenantsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/fees': typeof FeesRoute
  '/register': typeof RegisterRoute
  '/star-players': typeof StarPlayersRoute
  '/dashboard/batches': typeof DashboardBatchesRoute
  '/dashboard/fee-plans': typeof DashboardFeePlansRoute
  '/dashboard/fees': typeof DashboardFeesRoute
  '/dashboard/registrations': typeof DashboardRegistrationsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/site': typeof DashboardSiteRoute
  '/dashboard/students': typeof DashboardStudentsRouteWithChildren
  '/platform-admin/new': typeof PlatformAdminNewRoute
  '/platform-admin/subscriptions': typeof PlatformAdminSubscriptionsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/platform-admin': typeof PlatformAdminIndexRoute
  '/dashboard/students/$id': typeof DashboardStudentsIdRoute
  '/platform-admin/tenants/$id': typeof PlatformAdminTenantsIdRoute
  '/platform-admin/tenants': typeof PlatformAdminTenantsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/fees': typeof FeesRoute
  '/platform-admin': typeof PlatformAdminRouteWithChildren
  '/register': typeof RegisterRoute
  '/star-players': typeof StarPlayersRoute
  '/dashboard/batches': typeof DashboardBatchesRoute
  '/dashboard/fee-plans': typeof DashboardFeePlansRoute
  '/dashboard/fees': typeof DashboardFeesRoute
  '/dashboard/registrations': typeof DashboardRegistrationsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/site': typeof DashboardSiteRoute
  '/dashboard/students': typeof DashboardStudentsRouteWithChildren
  '/platform-admin/new': typeof PlatformAdminNewRoute
  '/platform-admin/subscriptions': typeof PlatformAdminSubscriptionsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/platform-admin/': typeof PlatformAdminIndexRoute
  '/dashboard/students/$id': typeof DashboardStudentsIdRoute
  '/platform-admin/tenants/$id': typeof PlatformAdminTenantsIdRoute
  '/platform-admin/tenants/': typeof PlatformAdminTenantsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/fees'
    | '/platform-admin'
    | '/register'
    | '/star-players'
    | '/dashboard/batches'
    | '/dashboard/fee-plans'
    | '/dashboard/fees'
    | '/dashboard/registrations'
    | '/dashboard/reports'
    | '/dashboard/site'
    | '/dashboard/students'
    | '/platform-admin/new'
    | '/platform-admin/subscriptions'
    | '/dashboard/'
    | '/platform-admin/'
    | '/dashboard/students/$id'
    | '/platform-admin/tenants/$id'
    | '/platform-admin/tenants/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/fees'
    | '/register'
    | '/star-players'
    | '/dashboard/batches'
    | '/dashboard/fee-plans'
    | '/dashboard/fees'
    | '/dashboard/registrations'
    | '/dashboard/reports'
    | '/dashboard/site'
    | '/dashboard/students'
    | '/platform-admin/new'
    | '/platform-admin/subscriptions'
    | '/dashboard'
    | '/platform-admin'
    | '/dashboard/students/$id'
    | '/platform-admin/tenants/$id'
    | '/platform-admin/tenants'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/fees'
    | '/platform-admin'
    | '/register'
    | '/star-players'
    | '/dashboard/batches'
    | '/dashboard/fee-plans'
    | '/dashboard/fees'
    | '/dashboard/registrations'
    | '/dashboard/reports'
    | '/dashboard/site'
    | '/dashboard/students'
    | '/platform-admin/new'
    | '/platform-admin/subscriptions'
    | '/dashboard/'
    | '/platform-admin/'
    | '/dashboard/students/$id'
    | '/platform-admin/tenants/$id'
    | '/platform-admin/tenants/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  FeesRoute: typeof FeesRoute
  PlatformAdminRoute: typeof PlatformAdminRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  StarPlayersRoute: typeof StarPlayersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/star-players': {
      id: '/star-players'
      path: '/star-players'
      fullPath: '/star-players'
      preLoaderRoute: typeof StarPlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform-admin': {
      id: '/platform-admin'
      path: '/platform-admin'
      fullPath: '/platform-admin'
      preLoaderRoute: typeof PlatformAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fees': {
      id: '/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof FeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform-admin/': {
      id: '/platform-admin/'
      path: '/'
      fullPath: '/platform-admin/'
      preLoaderRoute: typeof PlatformAdminIndexRouteImport
      parentRoute: typeof PlatformAdminRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/platform-admin/subscriptions': {
      id: '/platform-admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/platform-admin/subscriptions'
      preLoaderRoute: typeof PlatformAdminSubscriptionsRouteImport
      parentRoute: typeof PlatformAdminRoute
    }
    '/platform-admin/new': {
      id: '/platform-admin/new'
      path: '/new'
      fullPath: '/platform-admin/new'
      preLoaderRoute: typeof PlatformAdminNewRouteImport
      parentRoute: typeof PlatformAdminRoute
    }
    '/dashboard/students': {
      id: '/dashboard/students'
      path: '/students'
      fullPath: '/dashboard/students'
      preLoaderRoute: typeof DashboardStudentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/site': {
      id: '/dashboard/site'
      path: '/site'
      fullPath: '/dashboard/site'
      preLoaderRoute: typeof DashboardSiteRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/registrations': {
      id: '/dashboard/registrations'
      path: '/registrations'
      fullPath: '/dashboard/registrations'
      preLoaderRoute: typeof DashboardRegistrationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/fees': {
      id: '/dashboard/fees'
      path: '/fees'
      fullPath: '/dashboard/fees'
      preLoaderRoute: typeof DashboardFeesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/fee-plans': {
      id: '/dashboard/fee-plans'
      path: '/fee-plans'
      fullPath: '/dashboard/fee-plans'
      preLoaderRoute: typeof DashboardFeePlansRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/batches': {
      id: '/dashboard/batches'
      path: '/batches'
      fullPath: '/dashboard/batches'
      preLoaderRoute: typeof DashboardBatchesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/platform-admin/tenants/': {
      id: '/platform-admin/tenants/'
      path: '/tenants'
      fullPath: '/platform-admin/tenants/'
      preLoaderRoute: typeof PlatformAdminTenantsIndexRouteImport
      parentRoute: typeof PlatformAdminRoute
    }
    '/platform-admin/tenants/$id': {
      id: '/platform-admin/tenants/$id'
      path: '/tenants/$id'
      fullPath: '/platform-admin/tenants/$id'
      preLoaderRoute: typeof PlatformAdminTenantsIdRouteImport
      parentRoute: typeof PlatformAdminRoute
    }
    '/dashboard/students/$id': {
      id: '/dashboard/students/$id'
      path: '/$id'
      fullPath: '/dashboard/students/$id'
      preLoaderRoute: typeof DashboardStudentsIdRouteImport
      parentRoute: typeof DashboardStudentsRoute
    }
  }
}

interface DashboardStudentsRouteChildren {
  DashboardStudentsIdRoute: typeof DashboardStudentsIdRoute
}

const DashboardStudentsRouteChildren: DashboardStudentsRouteChildren = {
  DashboardStudentsIdRoute: DashboardStudentsIdRoute,
}

const DashboardStudentsRouteWithChildren =
  DashboardStudentsRoute._addFileChildren(DashboardStudentsRouteChildren)

interface DashboardRouteChildren {
  DashboardBatchesRoute: typeof DashboardBatchesRoute
  DashboardFeePlansRoute: typeof DashboardFeePlansRoute
  DashboardFeesRoute: typeof DashboardFeesRoute
  DashboardRegistrationsRoute: typeof DashboardRegistrationsRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardSiteRoute: typeof DashboardSiteRoute
  DashboardStudentsRoute: typeof DashboardStudentsRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBatchesRoute: DashboardBatchesRoute,
  DashboardFeePlansRoute: DashboardFeePlansRoute,
  DashboardFeesRoute: DashboardFeesRoute,
  DashboardRegistrationsRoute: DashboardRegistrationsRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardSiteRoute: DashboardSiteRoute,
  DashboardStudentsRoute: DashboardStudentsRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface PlatformAdminRouteChildren {
  PlatformAdminNewRoute: typeof PlatformAdminNewRoute
  PlatformAdminSubscriptionsRoute: typeof PlatformAdminSubscriptionsRoute
  PlatformAdminIndexRoute: typeof PlatformAdminIndexRoute
  PlatformAdminTenantsIdRoute: typeof PlatformAdminTenantsIdRoute
  PlatformAdminTenantsIndexRoute: typeof PlatformAdminTenantsIndexRoute
}

const PlatformAdminRouteChildren: PlatformAdminRouteChildren = {
  PlatformAdminNewRoute: PlatformAdminNewRoute,
  PlatformAdminSubscriptionsRoute: PlatformAdminSubscriptionsRoute,
  PlatformAdminIndexRoute: PlatformAdminIndexRoute,
  PlatformAdminTenantsIdRoute: PlatformAdminTenantsIdRoute,
  PlatformAdminTenantsIndexRoute: PlatformAdminTenantsIndexRoute,
}

const PlatformAdminRouteWithChildren = PlatformAdminRoute._addFileChildren(
  PlatformAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  FeesRoute: FeesRoute,
  PlatformAdminRoute: PlatformAdminRouteWithChildren,
  RegisterRoute: RegisterRoute,
  StarPlayersRoute: StarPlayersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
