-- Seed default automation rule templates for student.* lifecycle events (Phase 7.1).
-- Idempotent via template_key upsert.
INSERT INTO public.automation_rule_templates (template_key, name, description, category, audience, event_type, conditions, actions, default_enabled, priority)
VALUES
  ('student.registration_submitted.notify_owner',
    'New application received',
    'Notify owners and admins when a new registration is submitted.',
    'admissions', 'admin', 'student.registration_submitted',
    '[]'::jsonb,
    '[{"channel":"in_app","template":"New application from {{name}}"},{"channel":"push","template":"New application from {{name}}"}]'::jsonb,
    true, 10),
  ('student.registration_submitted.ack_applicant',
    'Application received acknowledgement',
    'Confirmation email/SMS to the applicant.',
    'admissions', 'applicant', 'student.registration_submitted',
    '[]'::jsonb,
    '[{"channel":"email","template":"Hi {{name}}, we received your application. We''ll be in touch soon."},{"channel":"whatsapp","template":"Hi {{name}}, we received your application at {{tenant_name}}."}]'::jsonb,
    true, 20),
  ('student.registration_approved.notify_applicant',
    'Application approved',
    'Notify the applicant with their activation link.',
    'admissions', 'applicant', 'student.registration_approved',
    '[]'::jsonb,
    '[{"channel":"email","template":"Welcome {{name}}! Activate your account: {{activation_link}}"},{"channel":"whatsapp","template":"Welcome to {{tenant_name}}! Activate: {{activation_link}}"}]'::jsonb,
    true, 10),
  ('student.registration_rejected.notify_applicant',
    'Application rejected',
    'Polite rejection notice.',
    'admissions', 'applicant', 'student.registration_rejected',
    '[]'::jsonb,
    '[{"channel":"email","template":"Hi {{name}}, unfortunately your application was not approved at this time."}]'::jsonb,
    true, 20),
  ('student.waitlisted.notify_applicant',
    'Waitlisted notice',
    'Notify applicant that they are on the waitlist.',
    'admissions', 'applicant', 'student.waitlisted',
    '[]'::jsonb,
    '[{"channel":"email","template":"Hi {{name}}, you''ve been placed on our waitlist. We''ll reach out when a slot opens."}]'::jsonb,
    true, 20),
  ('student.registration_changes_requested.notify_applicant',
    'Changes requested',
    'Ask the applicant for corrections or missing documents.',
    'admissions', 'applicant', 'student.registration_changes_requested',
    '[]'::jsonb,
    '[{"channel":"email","template":"Hi {{name}}, please review your application: {{notes}}"},{"channel":"in_app","template":"Please update your application: {{notes}}"}]'::jsonb,
    true, 10),
  ('student.imported.audit',
    'Bulk import audit',
    'Log bulk-imported students count.',
    'admissions', 'admin', 'student.imported',
    '[]'::jsonb,
    '[{"channel":"in_app","template":"Imported {{count}} students."}]'::jsonb,
    true, 30),
  ('student.activation_sent.audit',
    'Activation invites sent',
    'Log activation invitations sent to imported students.',
    'admissions', 'admin', 'student.activation_sent',
    '[]'::jsonb,
    '[{"channel":"in_app","template":"Sent {{count}} activation invites."}]'::jsonb,
    true, 30),
  ('student.activated.welcome',
    'Student activated welcome',
    'Welcome the student the moment they activate.',
    'admissions', 'student', 'student.activated',
    '[]'::jsonb,
    '[{"channel":"push","template":"Welcome aboard!"},{"channel":"in_app","template":"Your account is active. Explore your dashboard."}]'::jsonb,
    true, 10)
ON CONFLICT (template_key) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  event_type = EXCLUDED.event_type,
  actions = EXCLUDED.actions,
  updated_at = now();