// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dhxkvceqcupkuwblfeue.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRoeGt2Y2VxY3Vwa3V3YmxmZXVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODMyMzg1OTIsImV4cCI6MjA5ODgxNDU5Mn0.Rr4AdN72I6qKpQF677-9OjLiDrVRlph_ICMUmpCdIuk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});